### PR TITLE
Update MissionControl profile

### PR DESCRIPTION
**Pull request by MissionControlValidator**
Updated the `README.md` and the `full_validators.md` files

### CODE REVIEW

**Review by hanjukim — APPROVED** [review]

**Comment by MissionControlValidator** [comment]
Hi @hanjukim ,
Thank you for approving the pull request.

How long does it take to have the check at the end of our name on Terra Station?

Best regards,
[MissionControl](mcontrol.ml)

**Comment by hanjukim** [comment]
@simcheolhwan can you collaborate please.

**Comment by simcheolhwan** [comment]
It will be done in Monday

**Comment by MissionControlValidator** [comment]
Ok thanks

**Pull request merged**
